# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DWZ__HKophwxNCVKDiYL-XecWKDItgGe
"""

import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import zipfile
import os

# --- SCALE: 1.1 Million+ Records ---
NUM_USERS = 100000
NUM_TRANSACTIONS = 1000000
START_DATE = datetime(2023, 1, 1)
END_DATE = datetime(2025, 12, 31)

print("Starting generation... this may take a minute.")

# 1. USERS (dim_users)
user_ids = np.arange(100001, 100001 + NUM_USERS)
channels = ['TikTok', 'Meta', 'Google', 'Amazon Ads', 'YouTube']
regions = ['North America', 'EMEA', 'APAC', 'LATAM']
devices = ['iOS', 'Android', 'Web']

df_users = pd.DataFrame({
    'user_id': user_ids,
    'signup_timestamp': [START_DATE + timedelta(days=np.random.randint(0, 1095)) for _ in range(NUM_USERS)],
    'utm_source': np.random.choice(channels, NUM_USERS, p=[0.2, 0.25, 0.2, 0.15, 0.2]),
    'region': np.random.choice(regions, NUM_USERS),
    'device_type': np.random.choice(devices, NUM_USERS, p=[0.4, 0.4, 0.2])
})

# 2. TRANSACTIONS (fact_transactions)
categories = ['Electronics', 'Fashion', 'Home & Kitchen', 'Beauty', 'Sports']
trans_user_ids = np.random.choice(user_ids, NUM_TRANSACTIONS)

df_transactions = pd.DataFrame({
    'user_id': trans_user_ids,
    'order_value': np.round(np.random.uniform(20, 1000), 2),
    'shipping_cost': np.round(np.random.uniform(5, 50), 2),
    'is_refunded': np.random.choice([0, 1], NUM_TRANSACTIONS, p=[0.94, 0.06]),
    'category': np.random.choice(categories, NUM_TRANSACTIONS)
})

df_transactions['order_date'] = [START_DATE + timedelta(days=np.random.randint(0, 1095)) for _ in range(NUM_TRANSACTIONS)]
df_transactions['order_value'] = df_transactions['order_value'].apply(lambda x: f"$ {x:,.2f}")
df_transactions['shipping_cost'] = df_transactions['shipping_cost'].apply(lambda x: f"$ {x:,.2f}")

# 3. MARKETING (fact_marketing_spend)
marketing_rows = []
for d in pd.date_range(START_DATE, END_DATE):
    for c in channels:
        for camp_id in range(1, 11):
            spend = np.random.uniform(100, 2000)
            clicks = np.random.randint(500, 5000)
            impressions = clicks * np.random.randint(10, 50)
            marketing_rows.append([d, c, f"{c}_PROMO_{camp_id}", f"$ {spend:,.2f}", impressions, clicks])

df_marketing = pd.DataFrame(marketing_rows, columns=['date', 'utm_source', 'campaign_id', 'total_spend', 'impressions', 'clicks'])

# --- SAVE AND ZIP ---
files = {
    'dim_users.csv': df_users,
    'fact_transactions.csv': df_transactions,
    'fact_marketing_spend.csv': df_marketing
}

zip_name = "FAANG_Audit_Dataset_1M.zip"
with zipfile.ZipFile(zip_name, 'w', zipfile.ZIP_DEFLATED) as zipf:
    for filename, df in files.items():
        df.to_csv(filename, index=False)
        zipf.write(filename)
        os.remove(filename) # Clean up raw CSVs after zipping

print(f"SUCCESS: {zip_name} created with 1.1M+ rows of deep-dimension data.")